require "TCMusicDefenitions"

	GlobalMusic["CassetteMaruadaEDC"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaCast"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaHusk"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaAvoidableCause"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaKilter"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaSwathe"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaTenebrous"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaThatSong"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaReckoning"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaTrash"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteMaraudaUmbra"] = "tsarcraft_music_01_62"
